### ISSUE TITLE
Service Fabric 6.4 : How to achieve Support for Service Fabric Reliable Volumes that provide high availability through built-in replication?

### ISSUE THREAD

**Issue by sansindia85** [Azure-Samples/service-fabric-mesh#63]
I could not find information on how to achieve Support for Service Fabric Reliable Volumes that provide high availability through built-in replication. I'm using Visual Studio 2017 and Service Fabric Mesh SDK in Windows 10 V1709, what are the changes I need to do in volume.yaml and service.yaml. Please help/guide.

Counter App for Service Fabric Reliable Volumes is mentioned at  https://docs.microsoft.com/en-us/azure/service-fabric-mesh/service-fabric-mesh-howto-find-samples <- It does not have information on how to achieve Support for Service Fabric Reliable Volumes that provide high availability through built-in replication.

**Comment by ashishnegi** [comment]
@sansindia85 Here are the required volume changes : [windows](https://github.com/Azure-Samples/service-fabric-mesh/blob/master/templates/counter/counter.sfreliablevolume.windows.json#L53) and [Linux](https://github.com/Azure-Samples/service-fabric-mesh/blob/master/templates/counter/counter.sfreliablevolume.linux.json#L53)

Important point is `creationParameters` :
```
"creationParameters": {
                        "kind": "ServiceFabricVolumeDisk",
                        "sizeDisk": "Small"
                      },
```
`sizeDisk` can be `Small` ( `32GB`), `Medium` (`64GB`), `Large` (`128GB`).

**Comment by sansindia85** [comment]
Hi Ashish,

I downloaded your changes 
https://github.com/Azure-Samples/service-fabric-mesh/tree/6d54b028bc73ae4e5f57c6fa1af753bbae957e75

Can you please create a working sln which will point to counterSFVolume and counterService?
Based on my understanding, I made changes in app.yaml and volume.yaml. I greeted with the error as mentioned in screenshot.

![capture](https://user-images.githubusercontent.com/39188442/49632136-a5a5cb80-fa1a-11e8-855c-e80278f85e1b.PNG)

**Comment by ashishnegi** [comment]
@sansindia85 I am in the process of creating a Visual Studio solution for sf reliable volume.
To get you unblocked, with any mesh sample app, you need to add `volume` inline to your service like [here]( https://github.com/ashishnegi/service-fabric-mesh/blob/sfrv_yaml/src/counter/src/counterSFVolume/windows/App%20Resources/app.yaml#L14)
There is no other changes required.

Files written by the container on the `destinationPath` will be available after failover.

You can't use volume.yaml separately as sf reliable volume is tied to the service. It can't exist independently.

**Comment by raunakpandya** [comment]
Closing the issue. Please revert if you are still facing the issue.
