### ISSUE TITLE
Wrong region on the documentation to deploy the HelloWord

### ISSUE THREAD

**Issue by SamirFarhat** [Azure-Samples/service-fabric-mesh#64]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Deploy the HelloWord linux sample here https://github.com/Azure-Samples/service-fabric-mesh/tree/master/templates/helloworld

### Any log messages given by the failure
ERROR: The provided location 'eastus' is not available for resource type 'Microsoft.ServiceFabricMesh/gateways'. List of available regions for the resource type is 'eastasia'.

### Expected/desired behavior
The resource being deployed

### OS and Version?
Windows 10, Powershell

### Versions
10
### Mention any other details that might be useful
You need to update the documentation to use eastasia as a region
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by raunakpandya** [comment]
I think when you last tried, rollout must be going on and it should be working now. Please reopen the issue in case you still face it.
